version: "2.4"

services:
  app:
    build:
      context: .
    image: deno-app
    command: /bin/sh -c "./wait-for-it.sh db:5432 -- deno task dev"
    ports:
      - "3000:3000"
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      DB_NAME: ministock
      DB_USERNAME: postgres
      DB_PASSWORD: mostrans123
      DB_PORT: 5432
      DB_HOST: localhost
      REGION: ap-southeast-1
      SECRET_NAME: env-rds-dev
      MICROSOFT_GRAPH_LOGIN_URL: "https://login.microsoftonline.com/b59e9f7f-02bd-445a-8e3b-5a878c138dad/oauth2/v2.0/token"
      MICROSOFT_GRAPH_SCOPE: "https://graph.microsoft.com/.default"
      MICROSOFT_GRAPH_CLIENT_ID: b6277131-59e9-482b-aed9-b7f9ae1fe255
      MICROSOFT_GRAPH_CLIENT_SECRET: "oNJ8Q~RK~rQ6md9eduHroxmS~p00-q0S5iekqcD-"
      MICROSOFT_GRAPH_GRANT_TYPE: client_credentials
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
